version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    image: votre_nom_utilisateur_docker_hub/backend:latest
    ports:
      - "3001:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/mydb

  frontend:
    image: votre_nom_utilisateur_docker_hub/frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres-data:
